/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fingertip_jnidemo_TestJNI */

#ifndef _Included_com_fingertip_jnidemo_TestJNI
#define _Included_com_fingertip_jnidemo_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fingertip_jnidemo_TestJNI
 * Method:    getHolleWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fingertip_jnidemo_TestJNI_getHolleWord
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
